version: "3.9"

services:
    db:
        image: postgres:15-alpine
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        volumes:
            - pgdata:/var/lib/postgresql/data
    
    researcher-api:
        build:
            context: ../src/Services/Researcher/Infrastrcuture/Researcher.Api
            dockerfile: Dockerfile
        restart: on-failure
        env_file:
            - .env
        environment:
            ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
        depends_on:
            db:
                condition: service_healthy
        ports:
            - ${RESEARCHER_API_PORT}:8080

volumes:
    pgdata: